# -*- coding: utf-8 -*- 
import xbmc

DAYS = { "Mon": xbmc.getLocalizedString( 11 ),
         "Tue": xbmc.getLocalizedString( 12 ),
         "Wed": xbmc.getLocalizedString( 13 ),
         "Thu": xbmc.getLocalizedString( 14 ),
         "Fri": xbmc.getLocalizedString( 15 ),
         "Sat": xbmc.getLocalizedString( 16 ),
         "Sun": xbmc.getLocalizedString( 17 )}

WEATHER_CODES = { 'Clearing shower'                 : '11',
                  'Cloudy'                          : '26',
                  'Cloud and wind increasing'       : '23',
                  'Cloud increasing'                : '26',
                  'Drizzle'                         : '11',
                  'Drizzle clearing'                : '32',
                  'Fog then sunny'                  : '20',
                  'Frost then sunny'                : '28',
                  'Hazy'                            : '21',
                  'Heavy rain'                      : '40',
                  'Heavy showers'                   : '12',
                  'Increasing sunshine'             : '32',
                  'Late shower'                     : '11',
                  'Late thunder'                    : '00',
                  'Mostly cloudy'                   : '26',
                  'Mostly sunny'                    : '30',
                  'Overcast'                        : '26',
                  'Possible shower'                 : '11',
                  'Possible thunderstorm'           : '00',
                  'Rain'                            : '40',
                  'Rain and snow'                   : '05',
                  'Rain clearing'                   : '39',
                  'Rain developing'                 : '12',
                  'Rain tending to snow'            : '05',
                  'Showers'                         : '11',
                  'Showers easing'                  : '11',
                  'Showers increasing'              : '11',
                  'Snow'                            : '41',
                  'Snowfalls clearing'              : '05',
                  'Snow develping'                  : '41',
                  'Snow showers'                    : '41',
                  'Snow tending to rain'            : '05',
                  'Sunny'                           : '32',
                  'Thunderstorms'                   : '38',
                  'Thunderstorms clearing'          : '37',
                  'Windy'                           : '23',
                  'Windy with rain'                 : '01',
                  'Windy with showers'              : '01',
                  'Windy with snow'                 : '13',
                  'Wind and rain increasing'        : '01',
                  'Wind and showers easing'         : '01',                                 
                  'Unknown'                         : 'na',
                  'nt_unknown'                      : 'na'}
